load("@rules_cc//cc:defs.bzl", "cc_library")

config_setting(
    name = "dbg",
    values = {"compilation_mode": "dbg"},
)

config_setting(
    name = "opt",
    values = {"compilation_mode": "opt"},
)

cc_library(
    name = "bx",
    srcs = glob(
        ["src/*.cpp"],
        exclude = [
            "src/amalgamated.cpp",
            "src/crtnone.cpp",
        ],
    ),
    hdrs = glob([
        "include/bx/*.h",
    ]) + select({
        "@platforms//os:linux": glob([
            "include/compat/linux/*.h",
        ]),
        "//conditions:default": [],
    }),
    copts = [
        "-march=native",
        "-pthread",
    ],
    cxxopts = ["-std=c++20"],
    defines = select({
        ":dbg": ["BX_CONFIG_DEBUG=1"],
        "//conditions:default": ["BX_CONFIG_DEBUG=0"],
    }),
    linkopts = [
        "-pthread",
        "-ldl",
        "-lrt",
    ],
    strip_include_prefix = "include",
    target_compatible_with = ["@platforms//os:linux"],
    textual_hdrs = glob([
        "include/bx/inline/*.inl",
    ]),
    visibility = ["//visibility:public"],
    deps = ["//3rdparty/ini"],
)
